version: "3.9"

services:
  imprenta_db:
    image: postgres:14-alpine
    working_dir: /app
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=imprenta_db
    volumes:
      - pg_12_data:/var/lib/postgresql/data
      - ./:/app
    restart: on-failure:3
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"

volumes:
  pg_12_data:
